# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kbookmarks': '@same'
    'frameworks/threadweaver': '@same'
    'frameworks/ki18n': '@same'
    'frameworks/kio': '@same'
    'frameworks/karchive': '@same'
    'libraries/phonon': '@same'
    'graphics/kdegraphics-mobipocket': '@same'

- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/purpose': '@same'
    'frameworks/breeze-icons': '@same'
    'graphics/libkexiv2': '@same'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/plasma-activities': '@same'
    'frameworks/kpty': '@same'

- 'on': ['Android']
  'require':
    'frameworks/kirigami': '@same'

Options:
  cppcheck-arguments: '--enable=warning,style,performance -DOKULAR_EXPORT_PLUGIN'
  cppcheck-ignore-files:
    - autotests
